.class public abstract Lhz8;
.super Lhn4;
.source "SourceFile"


# annotations
.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000@\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\u000e\n\u0002\u0008\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010 \n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\u0005\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\r\n\u0002\u0010\u000b\n\u0002\u0008\u0007\u0008&\u0018\u00002\u00020\u0001BA\u0012\u0006\u0010\u0003\u001a\u00020\u0002\u0012\u0006\u0010\u0004\u001a\u00020\u0002\u0012\u0008\u0010\u0006\u001a\u0004\u0018\u00010\u0005\u0012\u000e\u0010\u0008\u001a\n\u0012\u0004\u0012\u00020\u0005\u0018\u00010\u0007\u0012\u0006\u0010\n\u001a\u00020\t\u0012\u0006\u0010\u000c\u001a\u00020\u000b\u00a2\u0006\u0004\u0008\r\u0010\u000eJ\u000f\u0010\u000f\u001a\u0004\u0018\u00010\u0005\u00a2\u0006\u0004\u0008\u000f\u0010\u0010J\u0017\u0010\u0014\u001a\u00020\u00132\u0006\u0010\u0012\u001a\u00020\u0011H\u0016\u00a2\u0006\u0004\u0008\u0014\u0010\u0015R\u001c\u0010\u0006\u001a\u0004\u0018\u00010\u00058\u0016X\u0096\u0004\u00a2\u0006\u000c\n\u0004\u0008\u0016\u0010\u0017\u001a\u0004\u0008\u0018\u0010\u0010R\u001f\u0010\u0008\u001a\n\u0012\u0004\u0012\u00020\u0005\u0018\u00010\u00078\u0006\u00a2\u0006\u000c\n\u0004\u0008\u0019\u0010\u001a\u001a\u0004\u0008\u001b\u0010\u001cR\u0017\u0010\n\u001a\u00020\t8\u0006\u00a2\u0006\u000c\n\u0004\u0008\u001d\u0010\u001e\u001a\u0004\u0008\u001f\u0010 R\"\u0010$\u001a\u00020!8\u0006@\u0006X\u0086\u000e\u00a2\u0006\u0012\n\u0004\u0008\"\u0010#\u001a\u0004\u0008$\u0010%\"\u0004\u0008&\u0010\'\u00a8\u0006("
    }
    d2 = {
        "Lhz8;",
        "Lhn4;",
        "",
        "parentRemoteId",
        "remoteId",
        "Lah4;",
        "exerciseBaseEntity",
        "",
        "distractors",
        "Lcom/busuu/legacy_domain_model/DisplayLanguage;",
        "answerDisplayLanguage",
        "Lzbg;",
        "instructions",
        "<init>",
        "(Ljava/lang/String;Ljava/lang/String;Lah4;Ljava/util/List;Lcom/busuu/legacy_domain_model/DisplayLanguage;Lzbg;)V",
        "getProblemEntity",
        "()Lah4;",
        "Lcom/busuu/domain/model/LanguageDomainModel;",
        "courseLanguage",
        "Lqrg;",
        "validate",
        "(Lcom/busuu/domain/model/LanguageDomainModel;)V",
        "q",
        "Lah4;",
        "getExerciseBaseEntity",
        "r",
        "Ljava/util/List;",
        "getDistractors",
        "()Ljava/util/List;",
        "s",
        "Lcom/busuu/legacy_domain_model/DisplayLanguage;",
        "getAnswerDisplayLanguage",
        "()Lcom/busuu/legacy_domain_model/DisplayLanguage;",
        "",
        "t",
        "Z",
        "isAutoGeneratedFromClient",
        "()Z",
        "setAutoGeneratedFromClient",
        "(Z)V",
        "common"
    }
    k = 0x1
    mv = {
        0x2,
        0x0,
        0x0
    }
    xi = 0x30
.end annotation


# instance fields
.field public final q:Lah4;

.field public final r:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lah4;",
            ">;"
        }
    .end annotation
.end field

.field public final s:Lcom/busuu/legacy_domain_model/DisplayLanguage;

.field public t:Z


# direct methods
.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Lah4;Ljava/util/List;Lcom/busuu/legacy_domain_model/DisplayLanguage;Lzbg;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            "Lah4;",
            "Ljava/util/List<",
            "+",
            "Lah4;",
            ">;",
            "Lcom/busuu/legacy_domain_model/DisplayLanguage;",
            "Lzbg;",
            ")V"
        }
    .end annotation

    const-string v0, "parentRemoteId"

    invoke-static {p1, v0}, Lve7;->g(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "remoteId"

    invoke-static {p2, v0}, Lve7;->g(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "answerDisplayLanguage"

    invoke-static {p5, v0}, Lve7;->g(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "instructions"

    invoke-static {p6, v0}, Lve7;->g(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-direct {p0, p1, p2}, Lhn4;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    iput-object p3, p0, Lhz8;->q:Lah4;

    iput-object p4, p0, Lhz8;->r:Ljava/util/List;

    iput-object p5, p0, Lhz8;->s:Lcom/busuu/legacy_domain_model/DisplayLanguage;

    invoke-virtual {p0, p6}, Lhn4;->setInstructions(Lzbg;)V

    return-void
.end method


# virtual methods
.method public final getAnswerDisplayLanguage()Lcom/busuu/legacy_domain_model/DisplayLanguage;
    .locals 1

    iget-object v0, p0, Lhz8;->s:Lcom/busuu/legacy_domain_model/DisplayLanguage;

    return-object v0
.end method

.method public final getDistractors()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lah4;",
            ">;"
        }
    .end annotation

    iget-object v0, p0, Lhz8;->r:Ljava/util/List;

    return-object v0
.end method

.method public getExerciseBaseEntity()Lah4;
    .locals 1

    iget-object v0, p0, Lhz8;->q:Lah4;

    return-object v0
.end method

.method public final getProblemEntity()Lah4;
    .locals 1

    invoke-virtual {p0}, Lhz8;->getExerciseBaseEntity()Lah4;

    move-result-object v0

    return-object v0
.end method

.method public final isAutoGeneratedFromClient()Z
    .locals 1

    iget-boolean v0, p0, Lhz8;->t:Z

    return v0
.end method

.method public final setAutoGeneratedFromClient(Z)V
    .locals 0

    iput-boolean p1, p0, Lhz8;->t:Z

    return-void
.end method

.method public validate(Lcom/busuu/domain/model/LanguageDomainModel;)V
    .locals 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/busuu/android/common/course/exception/ComponentNotValidException;
        }
    .end annotation

    const-string v0, "courseLanguage"

    invoke-static {p1, v0}, Lve7;->g(Ljava/lang/Object;Ljava/lang/String;)V

    invoke-super {p0, p1}, Lf12;->validate(Lcom/busuu/domain/model/LanguageDomainModel;)V

    invoke-virtual {p0}, Lhz8;->getProblemEntity()Lah4;

    move-result-object p1

    invoke-static {}, Lcom/busuu/domain/model/LanguageDomainModel;->values()[Lcom/busuu/domain/model/LanguageDomainModel;

    move-result-object v0

    invoke-static {v0}, Lda0;->F0([Ljava/lang/Object;)Ljava/util/List;

    move-result-object v0

    invoke-virtual {p0, p1, v0}, Lf12;->c(Lah4;Ljava/util/List;)V

    iget-object p1, p0, Lhz8;->r:Ljava/util/List;

    invoke-static {}, Lcom/busuu/domain/model/LanguageDomainModel;->values()[Lcom/busuu/domain/model/LanguageDomainModel;

    move-result-object v0

    array-length v1, v0

    invoke-static {v0, v1}, Ljava/util/Arrays;->copyOf([Ljava/lang/Object;I)[Ljava/lang/Object;

    move-result-object v0

    invoke-static {v0}, Ljava/util/Arrays;->asList([Ljava/lang/Object;)Ljava/util/List;

    move-result-object v0

    const-string v1, "asList(...)"

    invoke-static {v0, v1}, Lve7;->f(Ljava/lang/Object;Ljava/lang/String;)V

    const/4 v1, 0x2

    invoke-virtual {p0, p1, v1, v0}, Lf12;->b(Ljava/util/List;ILjava/util/List;)V

    return-void
.end method
